camera0: 4
camera1: 6
frame_width: 1920
frame_height: 1080
mono_calibration_frames: 50
stereo_calibration_frames: 50
view_resize: 1
checkerboard_box_size_scale : 0.024
checkerboard_rows: 6
checkerboard_columns: 5
cooldown: 20

